# .github/workflows/lint.yml
name: Lint

on:
  push:
    branches-ignore:
      - "main"
      - "master"
  pull_request:
    branches-ignore:
      - "main"
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.7.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm run lint
