name: CI

on:
  push:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/actions/checkout@v4

      - uses: docker://ghcr.io/voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp fmt --check .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/actions/checkout@v4

      - uses: docker://ghcr.io/voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp build
